# Site
repository: hokfu/hokfu.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Khant Htoo Naing
title: Machine Learning Engineer
email: khanthtoonaing2000@gmail.com
website: https://hokfu.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: KhantHtooNaing2
github_username:  Hokfu
linkedin_username: khant-htoo-naing-31799a234

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Khant Htoo Naing. I am from Myanmar. I am currently studying IT in Thailand.<br>
  I am an enthusiastic individual in machine learning and AI. I enjoy exploring and inspecting through data and find solutions in it. 

  I am deeply interested in <mark>Machine Learning</mark> and <mark>Deep Learning</mark> with <mark>Python</mark>. I am also interested in <mark>Computer Vision</mark> and <mark>Natural Language Processing</mark>. I am familiar and have done projects with <mark>PyTorch</mark> and <mark>TensorFlow</mark> libraries and understand their workflows. My goal is to become a professional in the field of <mark>AI</mark> and <mark>Machine Learning</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Classification of energy consumption
        link: github.com/Hokfu/Flower-image-classification
        # link_text: Project Website
        additional_links:
          - title:  Flower Image Classification
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This project is  the start of my deep learning journey.
        description: | # this will include new lines to allow paragraphs
          I worked on this project as a capstone project while learning machine learning course. This project includes EDA, model training, evaluation and containarization of the model. I used Tensorflow and Keras to build a model that can classify between daisy and dandelion. I used a pre-trained model VGG16 and fine-tuned it to get the best results.
      - layout: top-middle
        title: Classification of energy consumption in steel company
        link: github.com/Hokfu/Energy-Consumption-Model
        # link_text: Project Website
        additional_links:
          - title:  Energy Load Type Classification
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is my capstone project for my machine learning course.
        description: | # this will include new lines to allow paragraphs
          This project is about classification of load type in a steel factory. This includes data preprocessing, EDA, model training, evaluation and deployment in Docker container. I tried different models such as logistic regression and random forest to evaluate the data and did hyper parameter tuning with random forest model. I used Flask to deploy the model in a Docker container.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Geni Asia
        link: https://geni.asia/
        # link_text: boringcompany.com
        sub_title: Research Internship
        caption: December 2023 - Present
        quote: >
         Researching existing LLMs and finding the most suitable model for Burmese language
        description: | # this will include new lines to allow paragraphs
            There are many different language models that are available for English language. However, there are not many researches on Burmese language. My team is currently researching on existing language models and finding the most suitable model for Burmese language. We are also working on fine-tuning the model to get the best results.
      - layout: left
        title: Rangsit University Internation College
        link: 
        # link_text: boringcompany.com
        sub_title: Teaching Assistant/Web Developer
        caption: December 2023 - Present
        quote: >
         Teaching assistant and web developer in Rangsit University International College
        description: | # this will include new lines to allow paragraphs
            I worked part time as a teaching assistant and web developer in Rangsit University International College for four months. This job involves helping students in developing simple web applications and my team also have to develop web apps for the college staffs and students.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Yangon Technological University
        caption: 2016 - 2020
        sub_title: Bachelor of Engineering (Computer Engineering and Information Technology)
        quote: >
          Yangon Technological University is one of the top universities in Myanmar.
        description: | # this will include new lines to allow paragraphs
          During my time at Yangon, I spent most of the time studying programming and computer science. However, due to the country's situation, I left the university in my fourth year and continued my studies in Thailand.
      - layout: left
        title: Rangsit University
        caption: 2022 - Current
        sub_title: Bachelor of Science (Information and Communication Technology)
        quote: >
          Rangsit University is a private university in Thailand.
        description: | # this will include new lines to allow paragraphs
          I continued studying in Rangsit University International College, Thailand. Here, I met amazing professors and friends who helped me to improve my skills and knowledge in IT.

  - title: Fun Facts More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in machine learning and AI, I also enjoy the following activities:
      - [Dota 2](https://www.dota2.com/home)
      - Football
      - Table Tennis

      I also enjoy reading books and watching movies and television series in my free time. I enjoy watching Dota 2 tournaments a lot. I also enjoy playing football and table tennis with my friends. My other interests include watching Chinese martial arts dramas. I can speak Burmese and English fluently and can speak Chinese for daily conversations.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
