# Site
repository: Hokfu/hokfu.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Khant Htoo Naing / Hokfu / Turtle
title: Machine Learning & Generative AI
email: khanthtoonaing2000@gmail.com
website: https://hokfu.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: KhantHtooNaing2
github_username: Hokfu
linkedin_username: khant-htoo-naing-31799a234

# About Section
# about_title: About Me
about_profile_image: images/profile_2.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Khant Htoo Naing. You can call me "Hokfu" or "Turtle". I am from Myanmar.<br><br>
  I am currently working as a Agentic AI Developer based in Thailand.<br><br>
  My other interests are <mark>Machine Learning</mark>, <mark>Deep Learning</mark>, <mark>MLOps</mark> and <mark>LLMOps</mark>.<br><br>
  I can program in <mark>Python</mark> and <mark>GoLang</mark>.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Yangon Technological University
        caption: 2016 - 2020 ( 4th year )
        sub_title: Bachelor of Engineering (Computer Engineering and Information Technology)
      - layout: top-middle
        title: Rangsit University, Rangsit International College, Thailand
        caption: 2022 - 2025 ( Graduated )
        sub_title: Bachelor of Science (Information and Communication Technology)
  - title: Skills
    layout: text
    content: <ul>
      <li>Python</li>
      <li>GoLang</li>
      <li>Agentic AI</li>
      <li>MLOps</li>
      <li>Machine Learning</li>
      </ul>
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Rangsit University Internation College
        link: www.rsuip.org
        sub_title: Teaching Assistant/Web Developer
        caption: December 2023 - April 2024
        description: |
          I worked part time as a teaching assistant and web developer in Rangsit University International College for four months. This job involves helping students in developing simple web applications and my team also have to develop web apps for the college staffs and students.
      - layout: left
        title: General Magick Industries
        link:
        sub_title: Agentic AI Developer
        caption: June 2024 - Present
        description: | # this will include new lines to allow paragraphs
          I develop different LLM applications with Generative AI. I also have to research different models and keep up with latest generative AI technologies, and find the most suitable model for different projects at the company.
  - title: Learnings
    layout: list
    content:
      - layout: top-middle
        title: Machine Learning Zoomcamp
        link: github.com/Hokfu/Machine_Learning_Camp
        caption: Machine Learning Zoomcamp from <a href="https://datatalks.club/">DataTalksClub</a>
      - layout: top-middle
        title: MLOps Zoomcamp
        link: github.com/Hokfu/MLOps_Zoomcamp_Study
        caption: MLOps Zoomcamp from <a href="https://datatalks.club/">DataTalksClub</a>
      - layout: top-middle
        title: LLM Zoomcamp
        link: github.com/Hokfu/LLM-Zoomcamp-Study
        caption: LLM Zoomcamp from <a href="https://datatalks.club/">DataTalksClub</a>
  - title: Personal Projects # Title for the section
    layout: list
    content:
      - layout: top-middle
        title: Campaign Success Prediction MLOps Project
        link: github.com/Hokfu/campaign_success_prediction_with_mlops
        additional_links:
          - title: Campagiagn Success Prediction MLOps Project
            icon: fab fa-github
            url: github.com/Hokfu/campaign_success_prediction_with_mlops
        description: |
          An end to end MLOps project for predicting campaign success. The project includes data collection, data preprocessing, model training, model evaluation, and model deployment, monitoring.
      - layout: top-middle
        title: Flower Image Classification
        link: github.com/Hokfu/Flower-image-classification
        additional_links:
          - title: Flower Image Classification
            icon: fab fa-github
            url: github.com/Hokfu/Flower-image-classification
        description: |
          I worked on this project as a capstone project while learning machine learning course. This project includes EDA, model training, evaluation and containarization of the model. I used Tensorflow and Keras to build a model that can classify between daisy and dandelion. I used a pre-trained model VGG16 and fine-tuned it to get the best results. The model is then deployed using Flask and containerzied with Docker.
      - layout: top-middle
        title: Classification of energy consumption in steel company
        link: github.com/Hokfu/Energy-Consumption-Model
        # link_text: Project Website
        additional_links:
          - title: Energy Load Type Classification
            icon: fab fa-github
            url: github.com/Hokfu/Energy-Consumption-Model
        description: |
          This project is about classification of load type in a steel factory.
          In this project, by checking the energy consumption, power consumption, weekday or weekend, the model is trained to predict the energy load type. The trained model is then deployed using Flask and containerized with Docker.
  - title: Languages
    layout: text
    content: <ul>
      <li>Burmese - Native</li>
      <li>English - Fluent</li>
      <li>Chinese - Intermediate</li>
      </ul>

# Footer
footer_show_references: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
